apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-11-29T01:30:55Z
  generation: 1
  labels:
    run: opencensus-demo-frontend
  name: opencensus-demo-frontend
  namespace: default
  resourceVersion: "1220091"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/opencensus-demo-frontend
  uid: 6adb9339-f376-11e8-8bdb-42010a8a0039
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: opencensus-demo-frontend
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"      # must be quoted
        prometheus.io/port: "8082" # must be quoted
        prometheus.io/path: "/metrics"      # it defaults to /metrics
      creationTimestamp: null
      labels:
        run: opencensus-demo-frontend
    spec:
      containers:
      - image: gcr.io/ygrinshteyn-sandbox/frontend:latest
        imagePullPolicy: Always
        name: opencensus-demo-frontend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: BACKENDHOST
          value: "opencensus-demo-backend"
        - name: BACKENDPORT
          value: "8080"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30