# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import basicmessage_pb2 as basicmessage__pb2


class backendStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendMessage = channel.unary_unary(
        '/basicMessage.backend/sendMessage',
        request_serializer=basicmessage__pb2.commString.SerializeToString,
        response_deserializer=basicmessage__pb2.commString.FromString,
        )


class backendServicer(object):
  """The greeting service definition.
  """

  def sendMessage(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_backendServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendMessage': grpc.unary_unary_rpc_method_handler(
          servicer.sendMessage,
          request_deserializer=basicmessage__pb2.commString.FromString,
          response_serializer=basicmessage__pb2.commString.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'basicMessage.backend', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
